name: Bilibili Fans Tracker

on:
  schedule:
    - cron: "0 16 * * *"  # UTC时间16:00执行（北京时间次日00:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  track:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        retry-on-error: true

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 安装依赖
      run: pip install -r requirements.txt

    # 关键修复：先拉取最新代码再运行脚本
    - name: 拉取最新代码
      run: |
        git config --global user.name 'Auto-Committer'
        git config --global user.email 'actions@users.noreply.github.com'
        git pull origin main

    - name: 运行脚本
      run: python main.py

    - name: 提交数据更新
      run: |
        # 检查文件是否有变更
        if git diff --quiet bilibili_fans_data.xlsx; then
          echo "数据无变化，跳过提交"
        else
          echo "检测到数据更新，正在提交..."
          git add bilibili_fans_data.xlsx
          git commit -m "自动更新粉丝数据 $(date +'%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin main  # 再次拉取以处理可能的冲突
          git push origin HEAD:main
          echo "✓ 数据已更新并推送"
        fi
