name: Bilibili Fans Tracker

on:
  schedule:
    - cron: "0 16 * * *"  # UTC时间16:00执行（北京时间次日00:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 安装依赖
      run: pip install -r requirements.txt

    - name: 运行脚本
      run: python main.py

    - name: 提交数据更新
      run: |
        git config --global user.name 'Auto-Committer'
        git config --global user.email 'actions@users.noreply.github.com'
        git pull origin main --allow-unrelated-histories --rebase
        git add bilibili_fans_data.xlsx
        git commit -am "自动更新粉丝数据 $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin HEAD:main --force