name: Bilibili Fans Tracker

on:
  schedule:
    - cron: "0 16 * * *"  # UTC时间16:00执行（北京时间次日00:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  track:
    runs-on: ubuntu-latest
    # 添加并发控制
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        # 关键：获取完整历史记录
        fetch-depth: 0
        # 使用 token 确保权限
        token: ${{ secrets.GITHUB_TOKEN }}
        # 添加重试逻辑
        retry-on-error: true

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 安装依赖
      run: pip install -r requirements.txt

    - name: 运行脚本
      run: python main.py

    - name: 提交数据更新
      run: |
        # 配置 Git 用户
        git config --global user.name 'Auto-Committer'
        git config --global user.email 'actions@users.noreply.github.com'
        
        # 拉取最新更改（使用 rebase 避免合并提交）
        git pull --rebase origin main
        
        # 添加并提交更改
        git add bilibili_fans_data.xlsx
        git commit -m "自动更新粉丝数据 $(date +'%Y-%m-%d %H:%M:%S')"
        
        # 推送更改
        git push origin HEAD:main